---
# General config.
gitlab_domain: gitlab.{{ domain_name }}
gitlab_external_url: "https://{{ gitlab_domain }}/"
gitlab_git_data_dir: "/var/opt/gitlab/git-data"
gitlab_edition: "gitlab-ce"
gitlab_version: ''
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_package_version_separator: '='
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
gitlab_pass: "weget2u"
reg_runner_token: "GR1348941tCuiBd-y4t1tt3Bd66xM"

# Dependencies
gitlab_dependencies:
  - curl
  - tzdata
  - perl
  - gnupg2
